Fix build-push-hello-world.yaml
Task fails to run due to missing tag:

```
tag does not exist: acr303.azurecr-test.io/hello-world:yd2
Error: failed to run step id: acb_step_1: Failed to push images successfully
```